### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by ghost** [LagLord/Solana-Wallet-Tracker-Crypto-NFT-sales-Discord-Bot#1]
Hello good evening, I'm interested in the wallet tracker but I can't get it to work, I need help
![image](https://user-images.githubusercontent.com/113653536/190543822-5c97b593-aae1-40b2-97f2-cd7524352f0a.png)

**Comment by LagLord** [comment]
Hello,
Try putting the try statement before the json.loads() call inside the get_block function as I haven't used a status code checking, the response might be empty or something else.
This might be able to solve the issue, let me know of any updates.

And also would you be interested in Testing my new extension that does the same thing, I would love to hear some thoughts.

**Comment by kernels131** [comment]
> Hello, Try putting the try statement before the json.loads() call inside the get_block function as I haven't used a status code checking, the response might be empty or something else. This might be able to solve the issue, let me know of any updates.
> 
> And also would you be interested in Testing my new extension that does the same thing, I would love to hear some thoughts.


Gm sir, I don't understand much English and I don't understand python either hahaha how should the code look like, can you write it to me?
 # Get the latest Block
async def get_block():
    while True:
        url = "https://public-api.solscan.io/block/last?limit=1"
        resp = requests.get(url, headers=headers)
        
        resp = json.loads(resp.text)
        global previous_hash
        print(resp)
        try:
            previous_hash = resp[0]["result"]["blockTime"]
            time_delta = time.time() - previous_hash
            print(time.time(), previous_hash, time_delta)
            return time_delta
        except:
            print("getting block time 1")
            await asyncio.sleep(1)

**Comment by kernels131** [comment]
and if I would love to be able to test your extension

**Comment by ghost** [comment]
Great, I was able to solve it thanks to you, what is the best time_to_track, so that I can notify you quickly?
Can more than 1 wallet be added?

**Comment by ghost** [comment]
And I'm really interested in trying that extension👀

**Comment by LagLord** [comment]
> Great, I was able to solve it thanks to you, what is the best time_to_track, so that I can notify you quickly? Can more than 1 wallet be added?

I tried using 10 min and 15 min periods they were accurate you could try 5 min as well.
Yea it's a Dictionary you can add as many as you want

**Comment by LagLord** [comment]
![Screenshot (21)](https://user-images.githubusercontent.com/78442933/190668400-a2f65e94-caec-4fd3-aaba-fac8e06862eb.png)
![Screenshot (22)](https://user-images.githubusercontent.com/78442933/190668409-4240494c-0ef2-47fb-84dd-839a26e38e4a.png)
![Screenshot (23)](https://user-images.githubusercontent.com/78442933/190668414-db120ec1-dd24-4868-85c9-64f37020de06.png)
> And I'm really interested in trying that extension👀

Something went wrong while paying the Chrome developer fee with my Debit card so I have applied for a new one would take a week or so. I will share you the link once it's been published.

**Comment by LagLord** [comment]
here the extension:
https://chrome.google.com/webstore/detail/solana-wallet-tracker-nft/hhjfamcgbbklnlflaheknfhigannbjjn?
